import type { NextPage } from "next";
import Head from "next/head";
import { SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Inner Child</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-end p-6">
        <SignedOut>
          <SignInButton mode="modal">
            <button className="btn">Sign in</button>
          </SignInButton>
        </SignedOut>
        <SignedIn>
          <UserButton afterSignOutUrl="/" />
        </SignedIn>
      </main>
    </>
  );
};

export default Home;
